### ISSUE TITLE
Add new curriculum

### ISSUE THREAD

**Issue by damayanthiHerath** [cepdnaclk/www.ce.pdn.ac.lk#43]
We need to add the document relavent to the new curriculum. Please add a hyperlink with the text "Curriculm -Effective from E22" in the Undergraduate Courses page, and direct the link to attached PDF. 
[Uploading curriculum-E22.pdf…]()

**Comment by NuwanJ** [comment]
@damayanthiHerath is it E/22 or E/21 ? In the PDF already uploaded by Thilina, it says Effective from E/21. (The file attached to this GitHub issue seems not accessible to me)
