### ISSUE TITLE
E22 Curriculum document title

### ISSUE THREAD

**Issue by damayanthiHerath** [cepdnaclk/www.ce.pdn.ac.lk#45]
The PDF title https://www.ce.pdn.ac.lk/courses/undergraduate/new-curriculum/ should be Course Structure - BScEngHons Degree Programme Specializing in Computer Engineering [Effective from **E/22]** Please correct it.

**Comment by Akilax0** [comment]
Do you need to change the pdf title (meaning show up a different pdf) or the permalink directing to it?

**Comment by damayanthiHerath** [comment]
I am attaching the relavent pdf herewith.
[Uploading computerengcurrculum22.pdf…]()

**Comment by NuwanJ** [comment]
@damayanthiHerath madam, you had to wait until a few seconds until the PDF get uploaded.

**Comment by Akilax0** [comment]
New pdf updated @damayanthiHerath  please check
